### ISSUE TITLE
Javascript sample

### ISSUE THREAD

**Issue by zugakousaku** [BlackDice/Cinema4D-Threejs-Exporter#2]
Thank you for a wonderful plugin! Is there a Javascript sample for displaying exported data?
I tried to display it using the following file, but it did not work..

https://threejs.org/examples/#webgl_loader_json_blender

**Comment by EskelCz** [comment]
Thanks :)
Here is a scene I'm using for testing purposes.
https://dl.dropboxusercontent.com/u/20969924/PreviewScene.zip

Be warned though, I just found out that animation export is somewhat broken. I'm pretty sure it was working in some (at least limited) fashion in earlier builds. I'll investigate when I get to it.
Unfortunately I'm not working with Three.js as much anymore, therefore my motivation went down a lot.

**Comment by zugakousaku** [comment]
Thank You!
Your sample is very helpful for me. Currently this is the only way to export directly from Cinema 4D to Threejs.

**Comment by EskelCz** [comment]
You can also try these editors:
https://threejs.org/editor/
https://clara.io/
http://nunustudio.org/
