### ISSUE TITLE
Material support

### ISSUE THREAD

**Issue by sasha240100** [BlackDice/Cinema4D-Threejs-Exporter#3]
Any plans on making of materials export support?

**Comment by EskelCz** [comment]
Unfortunately not. I'm not as active with Three.js as I used to be, so I guess someone else has to carry the torch forward.  Sorry

**Comment by sasha240100** [comment]
Maybe we can. Can you at least point is where to look in your code and
where to start from?

**Comment by EskelCz** [comment]
It's similar to all the other types of data.
In exporter.py try to get materials from base document with this function:
https://developers.maxon.net/docs/Cinema4DPythonSDK/html/modules/c4d.documents/BaseDocument/index.html?highlight=materials#BaseDocument.GetMaterials
Here is the reference for the C4D material:
https://developers.maxon.net/docs/Cinema4DPythonSDK/html/modules/c4d/C4DAtom/GeListNode/BaseList2D/BaseMaterial/Material/index.html?highlight=material
Not sure if it has all the data that would be needed.

Then you have to figure out which materials are active on the mesh, probably by tags on the active object.
https://developers.maxon.net/docs/Cinema4DPythonSDK/html/modules/c4d/C4DAtom/GeListNode/BaseList2D/BaseObject/index.html?highlight=object#BaseObject.GetTags

Then you have to figure out how to parse the data to json into values that three.js understands.
If you can make that happen, I can probably find some time to do the UI work to finish it off.
