### ISSUE TITLE
In R17 unable to see plugin

### ISSUE THREAD

**Issue by archivum** [BlackDice/Cinema4D-Threejs-Exporter#6]
I'm unable to see the plugin when navigating to the 'plugins' interface. I've dropped all files properly into my C4D Plugins folder. Is there anything else that needs to be activated in R17 to make this appear.

**Comment by EskelCz** [comment]
Nothing else, just copy the files and restart the program. It should be in the Plugins menu.
Do you have the files in a sub-folder or all in the root?
It worked for me on multiple computers, with version R17.

**Comment by stu84151** [comment]
Hi EskelCz,

Thank you so much for sharing this plug-in, I am desperate to export c4d to tree.js!

However I am pretty new and running into issues... same  as Archivum, I see nothing in my plugin menu, instead it shows up in my Python's plugin manager.
![screen shot 2017-05-24 at 12 26 14 pm](https://cloud.githubusercontent.com/assets/28934093/26421958/d871563c-407c-11e7-8444-f093e921dca8.png)

Even so, it does not do anything when I double click it. 

I am trying to figure out what's not working. Could you give me some suggestion? Anything will be appreciated! I have Python 2.7, but my c4d is 12.0, after research I still can't tell if 12.0 is R17 or not.

**Comment by stu84151** [comment]
I just download the demo R18 of C4d, and the plug-in shows up! My 12.0 must be older than R17 then. 

But the animation option is in grey and can't be selected. My work is basically some lines mimicking the wave movement, pretty simple, and I have both baked and unbaked layer. Is there anything I should fixe so I can export the work? 

Thank you in advance.

**Comment by EskelCz** [comment]
R12 is definitely too old, it even has older version of python bundled with it.
Animation is thus far only supported for bones (skinned meshes) and even that is somewhat broken now.
I'm afraid that I won't get into repairing it, now that web assembly is beginning to be a thing. We'll see.
Sorry that I can't be more helpful.

**Comment by stu84151** [comment]
Hello EskelCz,

Thank you for replying me and helping with this issue. The latest C4d is over my budget, and it sounds like three.js is not the best one for me either. 

I am currently trying to export my c4d wave animation (composed by lines only) into .ai frame by frame, and then use adobe animate to make them into animation again. It's kind of problematic and adobe animate keeps crashing, but I think this may be so far what I can do.

Thank you for developing this plugin, even thought I can't use it, I still appreciate your contribution, and feel very thankful about being supported and helped by you. : )
 
Hope you have a good one and I will see you somewhere on the internet again!

**Comment by autuus** [comment]
I was able to get it working on r17 by updating the software
