### ISSUE TITLE
nothing happens when i click export

### ISSUE THREAD

**Issue by flowen** [BlackDice/Cinema4D-Threejs-Exporter#7]
hi! I followed your instructions, I see the plugin, but when choosing a location (also when not choosing a location) I see the rainbow of death and then it returns to a normal cursor - nothing has happened. No file, no message. The window of the plugin is still open. 

I'm using R14
with this STL model: http://threedscans.com/shell/chiragra-spider-conch/

**Comment by EskelCz** [comment]
Is there something in the developer console?
Also what's that rainbow of death? Can you record or screenshot it? Sounds like some graphics glitch/other hardware problem.

**Comment by flowen** [comment]
The rainbow spinner of death = https://www.google.co.th/search?q=rainbow+of+death+macos&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiosYW17sLVAhUJv48KHc-EBJcQ_AUICigB&biw=1680&bih=927 ;)

this is the output from console while trying to export with threejs export plugin:
![screen shot 2017-08-07 at 00 48 20](https://user-images.githubusercontent.com/4084169/29005662-2a7123be-7b0a-11e7-8519-7cab48c7e094.png)

**Comment by EskelCz** [comment]
Are you trying to export bones and weights of an object that doesn't have them?
Most of the exporting relies on tags, you can also see that UV tag is not found, that might be a problem as well. Please try to add one to the mesh, even if it's empty.

The crash occurred while trying to export vertex normals. Check the topology (ideally it should be all triangles and closed) and if it does the same thing, try the other vertex method.
