### ISSUE TITLE
exporting whole scene

### ISSUE THREAD

**Issue by autuus** [BlackDice/Cinema4D-Threejs-Exporter#9]
I could only find this useful if i could export the whole scene with animations, but it seems that i can export only 1 object, and yes, i successfully exported 1 if the scene objects without animations. oh well, if you fail, fail fast.
it seens that the exporter is capeable of exporting animations too, how do i do this?

**Comment by EskelCz** [comment]
Hi. The mesh has to have bones, weights and skeletal animation. But I'm afraid it's bugged anyway, it might work for some animations but not another. Unfortunately I'm no longer involved in developing for Three.js, so I'm hoping for someone knowledgeable to take over this project.

For whole scene export your best chance is by using Collada exporter. This is not in the scope of this project and probably never will. Sorry to say but the intersection between Three.js and Cinema 4D user bases seems too small for supporting this type of work. At this time anyway.
